apiVersion: v1
kind: Service
metadata:
  name: sample-tomcat-service
  labels:
    app: sample-tomcat-application
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: sample-tomcat-application
